---
title: "Exercise 5"
author: "Your Name"
date: '`r format(Sys.time(), "%d %b %Y")`'
output: pdf_document
---

```{r}
weather <- read.csv("ozone.csv")
```


+ Plot Ozone versus Solar Radiation, Wind Speed and Temperature on separate graphs
    - save the plot to a pdf file
    
```{r}
pdf("ozoneCorrelations.pdf")
par(mfrow=c(1,3))
plot(weather$Solar.R, weather$Ozone, pch=16,
     col="lightgreen", ylab="Ozone level",
     xlab="Solar Radiation")
plot(weather$Wind, weather$Ozone, pch=15, 
     col="steelblue", ylab="Ozone level", 
     xlab="Wind Speed")
plot(weather$Temp,weather$Ozone, pch=17,
     col="orange", ylab="Ozone level",
     xlab="Temperature")
dev.off()
```


+ Repeat the plot of Ozone versus Temperature and use a different colour to highlight any points with Ozone level > 100


```{r}
highO <- which(weather$Ozone > 100)
lowO <- which(weather$Ozone < 100)

plot(weather$Temp,weather$Ozone, type="n",
     ylab="Ozone level",
     xlab="Temperature")
points(weather$Temp[highO],weather$Ozone[highO],
       col="red",pch=17)
points(weather$Temp[lowO],weather$Ozone[lowO],
       col="orange",pch=17)
abline(h=100,lty=2)
legend("topleft", legend = c("Ozone > 100","Normal Ozone"),col=c("red","orange"),pch=17)
```

```{r}
mycol <-rep("orange",nrow(weather))
highO <- which(weather$Ozone > 100)
mycol[highO] <- "red"
mypch <- rep(17, nrow(weather))
mypch[highO] <- 18
plot(weather$Temp,weather$Ozone, 
     col=mycol, pch=mypch,ylab="Ozone level",
     xlab="Temperature")
abline(h=100,lty=2)
legend("topleft", legend = c("Ozone > 100","Normal Ozone"),col=c("red","orange"),pch=17)
```

Defining a variable for the cut-off makes our code a bit more flexible

```{r}
mycol <-rep("orange",nrow(weather))
cutoff <- 100
highO <- which(weather$Ozone > cutoff)
mycol[highO] <- "red"
mypch <- rep(17, nrow(weather))
mypch[highO] <- 18
plot(weather$Temp,weather$Ozone, 
     col=mycol, pch=mypch,ylab="Ozone level",
     xlab="Temperature")
abline(h=cutoff,lty=2)
legend("topleft", legend = c("Ozone > 100","Normal Ozone"),col=c("red","orange"),pch=17)
```

