---
title: "Analysis of My Gene List"
author: "Mark Dunning"
date: "9 September 2015"
output: html_document
---



```{r cache=TRUE}
genes <- read.delim("gene.description.txt")
subjects <- read.delim("cancer.patients.txt")
evals <- read.delim("gene.expression.txt",stringsAsFactors = FALSE)
```

`r ncol(evals)` patients were involved in this study.

```{r}
evals <- evals[,match(subjects$samplename,colnames(evals))]
```

```{r}
genelist <- c("ESR1", "NAT1", "SUSD3","SLC7A2" ,"SCUBE2")
stats <- NULL
for(i in 1:length(genelist)){
  
  probes <- genes[match(genelist[i],genes[,2]),1]
  j <- match(probes,rownames(evals))
  
  if(length(probes)>0){
   tmp <- t.test(as.numeric(evals[j,])~factor(subjects$er))
   stats[i] <- tmp$statistic
   boxplot(as.numeric(evals[j,])~factor(subjects$er),main=genelist[i],xlab="ER Status")
  }
  
}
stats
```


```{r}
probes <- genes[match(genelist,genes[,2]),1]
exprows <- match(probes,rownames(evals))
sampcol <- rep("blue", ncol(evals))
sampcol[subjects$er == 1 ] <- "yellow"
heatmap(as.matrix(evals[exprows,]),ColSideColors = sampcol)
  
```

